server:
   port: 8090
spring:
   application:
      name: ws-organizaciones
   mvc:
      servlet:
         path: /ws-organizaciones
   datasource:
      url: jdbc:mysql://localhost:3306/organizaciones?useSSL=false&serverTimezone=UTC
      username: root
      password: null
      driver-class-name: com.mysql.cj.jdbc.Driver
   jpa:
      properties:
         hibernate:
            show_sql: true
            use_sql_comments: true
            format_sql: true
            use-new-id-generator-mappings: true
            dialect: org.hibernate.dialect.MySQL5Dialect
loggin:
   level:
      root: WARN
      org:
         springframework:
            web: DEBUG
         hibernate: ERROR
   pattern:
      console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
jwt:
   header: Authorization
   secret: mySecret
   expiration: 6000
   route:
      authentication:
         path: /auth
         refresh: /refresh
secure:
   idExterno:
      prefijo: NE